#!/bin/bash

PROJECT_HOME=$( "$( dirname "$0" )/../../../.tasks/project-home" ) || exit 1

if [ "$1" == "help" ]
then
    echo "Usage: $0 [<command>]"
    echo "Commands:"
    echo "  help"
    echo "    This help page"
    echo "  run"
    echo "    Run all tasks"
    exit 0
elif [ "$1" != "" ] && [ "$1" != "run" ]
then
    echo "Error: $1: Unknown command"
fi
 
cd "$PROJECT_HOME"/containers/api || exit 1

echo "---| Install dependencies "
npm install

echo "---| Running Lint "
./tasks/lint run || exit 1

echo "---| Build and publish docker images"
./tasks/docker run || exit 1
