#!/bin/bash

PROJECT_HOME=$( "$( dirname "$0" )/../../../.tasks/project-home" ) || exit 1

if [ "$1" == "help" ]
then
    echo "Usage: $0 [<command>]"
    echo "Commands:"
    echo "  help"
    echo "    This help page"
    echo "  run"
    echo "    Run all tasks"
    exit 0
elif [ "$1" != "" ] && [ "$1" != "run" ]
then
    echo "Error: $1: Unknown command"
fi
 
cd "$PROJECT_HOME"/containers/factorial-calc || exit 1

echo "---| Install dependencies "
"$PROJECT_HOME"/.tasks/tools/deno run cache api.ts

echo "---| Running lint "
./tasks/lint run || exit 1

echo "---| Running unit tests"
"$PROJECT_HOME"/.tasks/tools/deno run test || exit 1