@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(personUser, "User", "Arbitrary consumer")
System(systemAlias, "tutorial-azure-aca", "Collection of rudimentary calculations")

Rel(personUser, systemAlias, "calculation request")

@enduml
