name: build-and-deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  lint-bash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Lint bash scripts
        run: ./scripts/lint-bash.sh

  build-api-container:
    runs-on: ubuntu-latest
    needs: [lint-bash]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install node dependencies
        run: |
          cd ./containers/api
          npm install

      - name: Lint code base
        run: |
          cd ./containers/api
          npm run lint

      - name: Create docker image
        run: ./scripts/api-docker-image.sh

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Publish docker image
        run: ./scripts/api-publish-docker-image.sh

  build-ackermann-calc-container:
    runs-on: ubuntu-latest
    needs: [lint-bash]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: |
          cd ./containers/ackermann-calc
          ./gradlew build

      - name: Create docker image
        run: ./scripts/ackermann-calc-docker-image.sh

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Publish docker image
        run: ./scripts/ackermann-calc-publish-docker-image.sh

  build-factorial-calc-container:
    runs-on: ubuntu-latest
    needs: [lint-bash]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Lint factorial-calc
        run: ./scripts/factorial-calc-lint-deno.sh

      - name: Create docker image
        run: ./scripts/factorial-calc-docker-image.sh

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Publish docker image
        run: ./scripts/factorial-calc-publish-docker-image.sh

  build-fibonacci-calc-container:
    runs-on: ubuntu-latest
    needs: [lint-bash]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Unit tests
        run: |
          cd ./containers/fibonacci-calc/test
          dotnet test

      - name: Create docker image
        run: ./scripts/fibonacci-calc-docker-image.sh

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Publish docker image
        run: ./scripts/fibonacci-calc-publish-docker-image.sh

  build-azure-infrastructure:
    runs-on: ubuntu-latest
    needs: [build-api-container, build-ackermann-calc-container, build-factorial-calc-container, build-fibonacci-calc-container]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set PRINCIPAL ID
        run: |
          PRINCIPAL_ID=`echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.clientId'`
          echo "PRINCIPAL_ID=$PRINCIPAL_ID" >> $GITHUB_ENV

      - name: Setup environment
        run: ./scripts/configure-environment.sh

      - name: Commit log
        if: always()
        run: |
          cd ./src/infra
          git add ./*.log
          if ! git diff-index --quiet HEAD --; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git commit -m "build: update changelog log"
            git push
          fi

  nudge-api:
    runs-on: ubuntu-latest
    needs: [build-azure-infrastructure]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Nudge
        run: |
          cd ./src/infra
          ./007-create-container-api.up

  nudge-ackermann-calc:
    runs-on: ubuntu-latest
    needs: [build-azure-infrastructure]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Nudge
        run: |
          cd ./src/infra
          ./005-create-container-ackermann-calc.up

  nudge-factorial-calc:
    runs-on: ubuntu-latest
    needs: [build-azure-infrastructure]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Nudge
        run: |
          cd ./src/infra
          ./004-create-container-factorial-calc.up

  nudge-fibonacci-calc:
    runs-on: ubuntu-latest
    needs: [build-azure-infrastructure]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Nudge
        run: |
          cd ./src/infra
          ./006-create-container-fibonacci-calc.up
